#!/usr/bin/env bash
# CIS Debian 13 coverage reconciliation between the two homelab repos.
#
# Cross-references:
#   * the per-recommendation status tables in the cis-benchmark repo
#     (docs/cyclops-debian-13-base/**/*.md)
#   * the `cis_<id>` task tags across the ansible repo's per-OS playbooks
#     (playbooks/os-*.yml + patch-*.yml) via `ansible-playbook --list-tags`
#
# Regenerates the coverage matrix in the cis-benchmark repo
# (docs/cyclops-debian-13-base/coverage.md) and, with --check, exits non-zero on
# a traceability gap: a recommendation marked implemented (:heavy_check_mark:)
# that has no matching tag, or one still marked :x:.
#
# Repo locations default to siblings of this script under ~/repos/homelab;
# override with $ANSIBLE_DIR / $CIS_BENCHMARK_DIR. Needs `ansible-playbook` on
# PATH (run it from the ansible dev shell).
#
# Usage: cis-coverage.sh [--check]

set -euo pipefail

LOG_TAG="[cis-coverage]"
log() { printf '%s %s\n' "$LOG_TAG" "$*"; }
warn() { printf '%s %s\n' "$LOG_TAG" "$*" >&2; }
die() {
    warn "ERROR: $*"
    exit 1
}

check=0
for arg in "$@"; do
    case "$arg" in
        --check) check=1 ;;
        -h | --help)
            grep -E '^# ' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) die "unknown argument: $arg (try --help)" ;;
    esac
done

# homelab/ is three levels up from scripts/scripts/cis/cis-coverage.sh
homelab="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ansible_dir="${ANSIBLE_DIR:-$homelab/ansible}"
benchmark_dir="${CIS_BENCHMARK_DIR:-$homelab/cis-benchmark}"

inventory="$ansible_dir/inventories/test"
bench_docs="$benchmark_dir/docs/cyclops-debian-13-base"
out="$bench_docs/coverage.md"

shopt -s nullglob
# the per-OS leaf playbooks (site.yml / patch.yml just import these)
playbooks=("$ansible_dir"/playbooks/os-*.yml "$ansible_dir"/playbooks/patch-*.yml)
shopt -u nullglob

[[ ${#playbooks[@]} -gt 0 ]] || die "no os-*/patch-* playbooks found in $ansible_dir/playbooks"
[[ -d "$bench_docs" ]] || die "benchmark docs not found: $bench_docs"
command -v ansible-playbook >/dev/null || die "ansible-playbook not on PATH (enter the ansible dev shell)"

# --- 1. cis_<id> tags present across the playbooks ------------------------
declare -A have_tag=()
while IFS= read -r tag; do
    [[ -n "$tag" ]] && have_tag["$tag"]=1
done < <(
    cd "$ansible_dir" && for pb in "${playbooks[@]}"; do
        ansible-playbook -i "$inventory" "$pb" --list-tags 2>/dev/null
    done | grep -oE 'cis_[0-9]+(\.[0-9]+)*' | sed 's/^cis_//' | sort -u
)
[[ ${#have_tag[@]} -gt 0 ]] || die "no cis_ tags found via --list-tags"

# echo the recommendation id, or the dotted prefix of it, that is a playbook
# tag; empty output means "not covered by any tag".
matching_tag() {
    local id="$1"
    while [[ -n "$id" ]]; do
        if [[ -n "${have_tag[$id]:-}" ]]; then
            printf '%s' "$id"
            return 0
        fi
        [[ "$id" == *.* ]] || break
        id="${id%.*}"
    done
}

# --- 2. statuses from the benchmark docs ----------------------------------
# awk parses each table row: strip whitespace, split on "|" into
#   f[1]="" (leading pipe)  f[2]=id  f[3]=level  f[4]=:symbol:
# shellcheck disable=SC2016  # $0/f are awk, not shell
mapfile -t rows < <(
    find "$bench_docs" -type f -name '*.md' ! -name 'coverage.md' -print0 |
        xargs -0 awk '
            {
                gsub(/[[:space:]]/, "", $0)
                split($0, f, "|")
                if (f[2] ~ /^[0-9]+(\.[0-9]+)+$/ && f[3] ~ /^[12]$/ && f[4] ~ /^:[a-z_]+:$/)
                    print f[2] "\t" f[3] "\t" f[4]
            }
        ' | awk '!seen[$0]++' | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n -k5,5n
)
[[ ${#rows[@]} -gt 0 ]] || die "no status rows parsed from $bench_docs"

# --- 3. classify and build the matrix -----------------------------------
declare -A label=(
    [":heavy_check_mark:"]="implemented"
    [":green_circle:"]="inherent"
    [":red_circle:"]="won't implement"
    [":black_circle:"]="can't implement"
    [":x:"]="UNIMPLEMENTED"
)
order=("implemented" "inherent" "won't implement" "can't implement" "UNIMPLEMENTED")

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

declare -A count=()
gaps=()
total=0

{
    printf '%s\n\n' "[Back](/docs/cyclops-debian-13-base/README.md)"
    printf '%s\n\n' "# Coverage"
    printf '%s\n\n' "<!-- generated by homelab-scripts scripts/cis/cis-coverage.sh - do not edit by hand -->"
    printf 'PLACEHOLDER_SUMMARY\n\n'
    printf '%s\n%s\n' "| Rec | Lvl | Status | Ansible tag |" "| :-- | :-: | :-- | :-- |"
} >"$tmp"

for row in "${rows[@]}"; do
    IFS=$'\t' read -r id level sym <<<"$row"
    lbl="${label[$sym]:-$sym}"
    total=$((total + 1))
    count["$lbl"]=$((${count["$lbl"]:-0} + 1))

    match="$(matching_tag "$id")"
    if [[ -n "$match" ]]; then
        tag="\`cis_${match}\`"
    else
        tag="-"
        [[ "$sym" == ":heavy_check_mark:" ]] && gaps+=("$id (implemented, no tag)")
    fi
    [[ "$sym" == ":x:" ]] && gaps+=("$id (unimplemented)")

    printf '| %s | %s | %s | %s |\n' "$id" "$level" "$lbl" "$tag" >>"$tmp"
done
printf '\n' >>"$tmp"

summary="$total recommendations:"
for k in "${order[@]}"; do
    [[ -n "${count[$k]:-}" ]] && summary+=" ${count[$k]} ${k},"
done
sed -i "s|PLACEHOLDER_SUMMARY|${summary%,}|" "$tmp"

mv "$tmp" "$out"
trap - EXIT

log "wrote $out ($total recommendations)"
for k in "${order[@]}"; do
    [[ -n "${count[$k]:-}" ]] && printf '%s %5d  %s\n' "$LOG_TAG" "${count[$k]}" "$k"
done

if [[ ${#gaps[@]} -gt 0 ]]; then
    warn "traceability gaps (${#gaps[@]}):"
    for g in "${gaps[@]}"; do warn "  - $g"; done
    [[ "$check" -eq 1 ]] && exit 1
fi
exit 0
